# Generated by Django 5.2 on 2025-04-07 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('sad', '😢 Xafa'), ('okay', '😐 Yaxshi'), ('happy', '😊 Quvnoq'), ('excited', '😁 Hayajonli'), ('angry', "😠 G'azablangan")], max_length=10)),
                ('stress_level', models.PositiveIntegerField()),
                ('sleep_quality', models.CharField(choices=[('poor', 'Yomon'), ('average', "O'rtacha"), ('good', 'Yaxshi')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
