# Generated by Django 5.2 on 2025-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('xafa', '😢 Xafa'), ('yaxshi', '😐 Yaxshi'), ('quvnoq', '😊 Quvnoq'), ('hayajonli', '😁 Hayajonli'), ("g'azablangan", "😠 G'azablangan")], max_length=15),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sleep_quality',
            field=models.CharField(choices=[('yomon', 'Yomon'), ("o'rtacha", "O'rtacha"), ('yaxshi', 'Yaxshi')], max_length=10),
        ),
    ]
